package config

// If false (lax mode), by default, nil matchers in spec generated its-structer
// will fallback to its.Always().
//
// If set true (strict mode), nil matchers fallback to its.Never()
var StrictModeForStruct = false

// When setting strict mode,
// nil fields in struct spec, generated by structer,
// fallback to its.Never() during test t.
//
// The configuration will be rolled back at the end of the test.
func StrictStructMatch(t interface{ Cleanup(func()) }, strict bool) {
	orig := StrictModeForStruct
	t.Cleanup(func() {
		StrictModeForStruct = orig
	})
	StrictModeForStruct = strict
}
